### ISSUE TITLE
Email subscription: no object DCH for MIME type multipart/alternative; 

### ISSUE THREAD

**Issue by blavenie** [duniter/duniter4j#13]
When send email trigger, get this error : 

```
org.duniter.core.exception.TechnicalException: Error while sending email to [benoit.lavenier@e-is.pro] using smtp config [username=cesium@le-sou.org, server=smtp.le-sou.org:587]: IOException while sending message
	at org.duniter.core.service.MailServiceImpl.sendEmail(MailServiceImpl.java:185)
	at org.duniter.core.service.MailServiceImpl.sendHtmlEmailWithText(MailServiceImpl.java:122)
	at org.duniter.elasticsearch.user.service.MailService.sendHtmlEmailWithText(MailService.java:101)
	at org.duniter.elasticsearch.subscription.service.SubscriptionService.lambda$processEmailSubscription$7(SubscriptionService.java:328)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at org.duniter.elasticsearch.threadpool.LoggingScheduledThreadPoolExecutor$LoggingTask.run(LoggingScheduledThreadPoolExecutor.java:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: javax.mail.MessagingException: IOException while sending message;
  nested exception is:
	javax.activation.UnsupportedDataTypeException: no object DCH for MIME type multipart/alternative; 
	boundary="----=_Part_1_1908556606.1495213245470"
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1167)
	at org.duniter.core.service.MailServiceImpl.sendEmail(MailServiceImpl.java:182)
	... 11 more
Caused by: javax.activation.UnsupportedDataTypeException: no object DCH for MIME type multipart/alternative; 
	boundary="----=_Part_1_1908556606.1495213245470"
	at javax.activation.ObjectDataContentHandler.writeTo(DataHandler.java:896)
	at javax.activation.DataHandler.writeTo(DataHandler.java:317)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1485)
	at javax.mail.internet.MimeMessage.writeTo(MimeMessage.java:1773)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1119)
	... 12 more
```

**Comment by blavenie** [comment]
seems to works from now
