### ISSUE TITLE
NullPointerException during indexation, on TX outputs

### ISSUE THREAD

**Issue by blavenie** [duniter/duniter4j#19]
```
[2017-07-20 00:27:13,809][INFO ][duniter.blockchain       ] [g1] [BASIC_MERKLED_API g1.duniter.org 10901] Indexing block #36709 - hash [000012FB81E4FB0038395B19D75ADC0B22A408DF5A506E509B5D41B02EF3AFE4]
java.lang.NullPointerException
        at org.duniter.core.client.model.bma.BlockchainBlocks.lambda$getTxRecipients$11(BlockchainBlocks.java:199)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
```

**Comment by blavenie** [comment]
linked to #17

**Comment by blavenie** [comment]
Reproduced on block 37895 : https://g1.duniter.fr/#/app/block/37895/00000A5899EEA5710D55CD004A091D9CA79A932BCEFBD492A631B84E58E15175
